<head>
<meta http-equiv="pragma" content="no-cache">
<meta http-equiv="cache-control" content="no-cache">
<meta http-equiv="content-language" content="ru">
<title>Крестики - нолики</title>
<meta name="keywords" content="игра,крестики,нолики">
<meta name="author" content="Смирнов Леонид">
<meta http-equiv="reply-to" content="smirnov-leonid@mail.ru">
<link rel="shortcut icon" href="picture/x0.ico">
</head>